# Form implementation generated from reading ui file 'dell.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dell(object):
    def setupUi(self, Dell):
        Dell.setObjectName("Dell")
        Dell.resize(311, 198)
        Dell.setMinimumSize(QtCore.QSize(311, 198))
        Dell.setMaximumSize(QtCore.QSize(311, 198))
        Dell.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"}\n"
"\n"
"QFormLayout {\n"
"    border: 1px solid black;\n"
"}")
        self.label_8 = QtWidgets.QLabel(parent=Dell)
        self.label_8.setGeometry(QtCore.QRect(10, -1, 141, 31))
        self.label_8.setStyleSheet("QLabel {\n"
"    \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_8.setObjectName("label_8")
        self.udel = QtWidgets.QPushButton(parent=Dell)
        self.udel.setGeometry(QtCore.QRect(180, 150, 120, 30))
        self.udel.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(255, 78, 78);\n"
"    transition: 0.5s;\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid black;\n"
"    border-radius:  10px;\n"
"    transition: 0.5s;\n"
"    font-size: 16px;\n"
"}")
        self.udel.setObjectName("udel")
        self.label = QtWidgets.QLabel(parent=Dell)
        self.label.setGeometry(QtCore.QRect(40, 30, 240, 31))
        self.label.setStyleSheet("QLabel {\n"
"    \n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dell)
        self.lineEdit.setGeometry(QtCore.QRect(90, 90, 120, 20))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"background-color: rgb(197, 197, 197);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dell)
        QtCore.QMetaObject.connectSlotsByName(Dell)

    def retranslateUi(self, Dell):
        _translate = QtCore.QCoreApplication.translate
        Dell.setWindowTitle(_translate("Dell", "Form"))
        self.label_8.setText(_translate("Dell", "Удаление цветка"))
        self.udel.setText(_translate("Dell", "Удалить ✖"))
        self.label.setText(_translate("Dell", "Название цветка который нужно удалить"))
