# Form implementation generated from reading ui file 'kalendark.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kalck(object):
    def setupUi(self, kalck):
        kalck.setObjectName("kalck")
        kalck.resize(500, 300)
        self.calll = QtWidgets.QCalendarWidget(parent=kalck)
        self.calll.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.calll.setObjectName("calll")

        self.retranslateUi(kalck)
        QtCore.QMetaObject.connectSlotsByName(kalck)

    def retranslateUi(self, kalck):
        _translate = QtCore.QCoreApplication.translate
        kalck.setWindowTitle(_translate("kalck", "Form"))
