# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1122, 684)
        Form.setMinimumSize(QtCore.QSize(1122, 684))
        Form.setMaximumSize(QtCore.QSize(1122, 684))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Form.setToolTipDuration(-1)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"}\n"
"")
        self.table_flower = QtWidgets.QTableWidget(parent=Form)
        self.table_flower.setGeometry(QtCore.QRect(0, 39, 947, 660))
        self.table_flower.setMouseTracking(False)
        self.table_flower.setStyleSheet("QTableWidget {\n"
"    border: 3px solid rgb(157, 91, 64);\n"
"    font-size:  12px;\n"
"    background-color: rgb(255, 238, 175);\n"
"}\n"
"")
        self.table_flower.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.table_flower.setRowCount(140)
        self.table_flower.setObjectName("table_flower")
        self.table_flower.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower.setHorizontalHeaderItem(4, item)
        self.table_flower.horizontalHeader().setVisible(True)
        self.table_flower.horizontalHeader().setCascadingSectionResizes(False)
        self.table_flower.horizontalHeader().setDefaultSectionSize(186)
        self.table_flower.verticalHeader().setVisible(True)
        self.addfl = QtWidgets.QPushButton(parent=Form)
        self.addfl.setGeometry(QtCore.QRect(950, 40, 170, 30))
        self.addfl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addfl.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(101, 219, 105);\n"
"    font-size:  16px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(20, 122, 23);\n"
"}\n"
"")
        self.addfl.setObjectName("addfl")
        self.pipfl = QtWidgets.QPushButton(parent=Form)
        self.pipfl.setGeometry(QtCore.QRect(950, 73, 170, 30))
        self.pipfl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pipfl.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(235, 21, 21);\n"
"    font-size:  16px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(153, 15, 15);\n"
"}")
        self.pipfl.setObjectName("pipfl")
        self.septfl = QtWidgets.QPushButton(parent=Form)
        self.septfl.setGeometry(QtCore.QRect(950, 106, 170, 30))
        self.septfl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.septfl.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(150, 150, 150);\n"
"    font-size:  16px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(66, 66, 66);\n"
"}")
        self.septfl.setObjectName("septfl")
        self.moifl = QtWidgets.QPushButton(parent=Form)
        self.moifl.setGeometry(QtCore.QRect(10, 5, 90, 36))
        self.moifl.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.moifl.setStyleSheet("QPushButton {\n"
"    border-radius:  0px;\n"
"    color: white;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(184, 4, 124);\n"
"    font-size:  14px;\n"
"}")
        self.moifl.setObjectName("moifl")
        self.segodnia = QtWidgets.QPushButton(parent=Form)
        self.segodnia.setGeometry(QtCore.QRect(130, 11, 130, 30))
        self.segodnia.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.segodnia.setStyleSheet("QPushButton {\n"
"    border-radius:  0px;\n"
"    color: white;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(245, 131, 0);\n"
"    font-size:  14px;\n"
"    set current index: -1000;\n"
"}")
        self.segodnia.setObjectName("segodnia")
        self.grpolivki = QtWidgets.QPushButton(parent=Form)
        self.grpolivki.setGeometry(QtCore.QRect(290, 8, 140, 33))
        self.grpolivki.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.grpolivki.setStyleSheet("QPushButton {\n"
"    border-radius:  0px;\n"
"    color: white;\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(23, 31, 255);\n"
"    font-size:  14px;\n"
"}\n"
"QPushButton:hover {\n"
"    top: 0px;\n"
"    height: 41px;\n"
"    transition: 0.5s;\n"
"}")
        self.grpolivki.setObjectName("grpolivki")
        self.table_flower2 = QtWidgets.QTableWidget(parent=Form)
        self.table_flower2.setGeometry(QtCore.QRect(0, 39, 947, 660))
        self.table_flower2.setMouseTracking(False)
        self.table_flower2.setStyleSheet("QTableWidget {\n"
"    border: 3px solid rgb(157, 91, 64);\n"
"    font-size:  12px;\n"
"    background-color: rgb(255, 238, 175);\n"
"}\n"
"")
        self.table_flower2.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.table_flower2.setRowCount(140)
        self.table_flower2.setObjectName("table_flower2")
        self.table_flower2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower2.setHorizontalHeaderItem(3, item)
        self.table_flower2.horizontalHeader().setVisible(True)
        self.table_flower2.horizontalHeader().setCascadingSectionResizes(False)
        self.table_flower2.horizontalHeader().setDefaultSectionSize(224)
        self.table_flower2.verticalHeader().setVisible(True)
        self.save = QtWidgets.QPushButton(parent=Form)
        self.save.setGeometry(QtCore.QRect(950, 40, 170, 30))
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 239, 255);\n"
"    font-size:  16px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(179, 233, 255);\n"
"}\n"
"")
        self.save.setObjectName("save")
        self.date3 = QtWidgets.QLabel(parent=Form)
        self.date3.setGeometry(QtCore.QRect(980, 10, 150, 20))
        self.date3.setStyleSheet("QLabel {\n"
"        font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.date3.setObjectName("date3")
        self.setdate = QtWidgets.QPushButton(parent=Form)
        self.setdate.setGeometry(QtCore.QRect(950, 40, 170, 30))
        self.setdate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.setdate.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 205, 160);\n"
"    font-size:  16px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 129, 56);\n"
"}\n"
"")
        self.setdate.setObjectName("setdate")
        self.table_flower3 = QtWidgets.QTableWidget(parent=Form)
        self.table_flower3.setGeometry(QtCore.QRect(0, 39, 947, 660))
        self.table_flower3.setMouseTracking(False)
        self.table_flower3.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.table_flower3.setStyleSheet("QTableWidget {\n"
"    border: 3px solid rgb(157, 91, 64);\n"
"    font-size:  12px;\n"
"    background-color: rgb(255, 238, 175);\n"
"}\n"
"")
        self.table_flower3.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_flower3.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.table_flower3.setShowGrid(True)
        self.table_flower3.setWordWrap(True)
        self.table_flower3.setCornerButtonEnabled(True)
        self.table_flower3.setRowCount(140)
        self.table_flower3.setObjectName("table_flower3")
        self.table_flower3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_flower3.setHorizontalHeaderItem(3, item)
        self.table_flower3.horizontalHeader().setVisible(True)
        self.table_flower3.horizontalHeader().setCascadingSectionResizes(False)
        self.table_flower3.horizontalHeader().setDefaultSectionSize(224)
        self.table_flower3.verticalHeader().setVisible(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.table_flower.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.table_flower.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.table_flower.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.table_flower.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.table_flower.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название"))
        item = self.table_flower.horizontalHeaderItem(1)
        item.setText(_translate("Form", "График поливки"))
        item = self.table_flower.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Где находится"))
        item = self.table_flower.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Объем воды"))
        item = self.table_flower.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Отличительные черты"))
        self.addfl.setToolTip(_translate("Form", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br/></pre></body></html>"))
        self.addfl.setText(_translate("Form", "Добавить цеток"))
        self.pipfl.setToolTip(_translate("Form", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br/></pre></body></html>"))
        self.pipfl.setText(_translate("Form", "Удалить цветок"))
        self.septfl.setToolTip(_translate("Form", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br/></pre></body></html>"))
        self.septfl.setText(_translate("Form", "Изменить цветок"))
        self.moifl.setText(_translate("Form", "Мои цветы"))
        self.segodnia.setText(_translate("Form", "Полить сегодня"))
        self.grpolivki.setText(_translate("Form", "График поливки"))
        item = self.table_flower2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.table_flower2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.table_flower2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.table_flower2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.table_flower2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название"))
        item = self.table_flower2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Где находится"))
        item = self.table_flower2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Объем воды"))
        item = self.table_flower2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Отличительные черты"))
        self.save.setToolTip(_translate("Form", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br/></pre></body></html>"))
        self.save.setText(_translate("Form", "Сохранить"))
        self.date3.setText(_translate("Form", "10-11-2024"))
        self.setdate.setToolTip(_translate("Form", "<html><head/><body><pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br/></pre></body></html>"))
        self.setdate.setText(_translate("Form", "Выбрать дату"))
        item = self.table_flower3.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.table_flower3.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.table_flower3.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.table_flower3.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.table_flower3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название"))
        item = self.table_flower3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Где находится"))
        item = self.table_flower3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Объем воды"))
        item = self.table_flower3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Отличительные черты"))
