# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Up(object):
    def setupUi(self, Up):
        Up.setObjectName("Up")
        Up.resize(603, 464)
        Up.setMinimumSize(QtCore.QSize(603, 464))
        Up.setMaximumSize(QtCore.QSize(603, 464))
        Up.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"}\n"
"")
        self.label_9 = QtWidgets.QLabel(parent=Up)
        self.label_9.setGeometry(QtCore.QRect(10, -1, 141, 31))
        self.label_9.setStyleSheet("QLabel {\n"
"    \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(parent=Up)
        self.label.setGeometry(QtCore.QRect(180, 35, 250, 31))
        self.label.setStyleSheet("QLabel {\n"
"    \n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Up)
        self.lineEdit.setGeometry(QtCore.QRect(210, 70, 200, 20))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"background-color: rgb(197, 197, 197);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.udel = QtWidgets.QPushButton(parent=Up)
        self.udel.setGeometry(QtCore.QRect(246, 109, 130, 30))
        self.udel.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(180, 252, 255);\n"
"    transition: 0.5s;\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid black;\n"
"    border-radius:  10px;\n"
"    transition: 0.5s;\n"
"    font-size: 12px;\n"
"}")
        self.udel.setObjectName("udel")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Up)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 150, 581, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"background-color: rgb(207, 207, 207);\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"background-color: rgb(207, 207, 207);\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"background-color: rgb(207, 207, 207);\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"background-color: rgb(207, 207, 207);\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"background-color: rgb(207, 207, 207);\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.udel_2 = QtWidgets.QPushButton(parent=Up)
        self.udel_2.setGeometry(QtCore.QRect(250, 410, 120, 30))
        self.udel_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"    transition: 0.5s;\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid black;\n"
"    border-radius:  10px;\n"
"    transition: 0.5s;\n"
"    font-size: 12px;\n"
"}")
        self.udel_2.setObjectName("udel_2")
        self.udel_3 = QtWidgets.QPushButton(parent=Up)
        self.udel_3.setGeometry(QtCore.QRect(470, 110, 120, 30))
        self.udel_3.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(184, 184, 184);\n"
"    transition: 0.5s;\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid black;\n"
"    border-radius:  10px;\n"
"    transition: 0.5s;\n"
"    font-size: 16px;\n"
"}")
        self.udel_3.setObjectName("udel_3")
        self.error = QtWidgets.QLabel(parent=Up)
        self.error.setGeometry(QtCore.QRect(10, 118, 224, 13))
        self.error.setStyleSheet("QLabel {    \n"
"    font: 10px \"MS Shell Dlg 2\";\n"
"    color: rgb(240, 41, 41);\n"
"}")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Up)
        QtCore.QMetaObject.connectSlotsByName(Up)

    def retranslateUi(self, Up):
        _translate = QtCore.QCoreApplication.translate
        Up.setWindowTitle(_translate("Up", "Form"))
        self.label_9.setText(_translate("Up", "Изменение цветка"))
        self.label.setText(_translate("Up", "Название цветка который нужно изменить"))
        self.udel.setText(_translate("Up", "Найти цветок   🔎 "))
        self.label_2.setText(_translate("Up", "Название цветка"))
        self.label_3.setText(_translate("Up", "Где находится"))
        self.label_4.setText(_translate("Up", "Необходимый объем воды"))
        self.label_5.setText(_translate("Up", "Отличительные черты"))
        self.label_6.setText(_translate("Up", "Поливать раз во сколько дней"))
        self.udel_2.setText(_translate("Up", "Изменить ⚙️"))
        self.udel_3.setText(_translate("Up", "Скрыть 🛠️"))
